parameters:
    jenko.house.controllers.outside.class: Jenko\HouseBundle\Controller\OutsideController
    jenko.house.controllers.enter_room.class: Jenko\HouseBundle\Controller\EnterRoomController

services:
    jenko.house.controllers.outside:
        class: %jenko.house.controllers.outside.class%
        arguments:
            - @templating

    jenko.house.controllers.enter_room:
        class: %jenko.house.controllers.enter_room.class%
        arguments:
            - @templating
            - @jenko.house.handlers.enter_room_handler

    jenko.house.handlers.enter_room_handler:
        class: Jenko\House\Handler\EnterRoomHandler
        arguments:
            - @jenko.house.adapters.symfony_event_dispatcher

    jenko.house.adapters.symfony_event_dispatcher:
        class: Jenko\House\Adapter\SymfonyEventDispatcherAdapter
        arguments:
            - @event_dispatcher

    jenko.house.subscribers.enter_room_subscriber:
        class: Jenko\House\Event\EnteredRoomSubscriber
        arguments:
            - @jenko.house.adapters.psr_logger
        tags:
            -  { name: kernel.event_subscriber }

    jenko.house.adapters.psr_logger:
        class: Jenko\House\Adapter\PsrLoggerAdapter
        arguments:
            - @logger
            