parameters:
    jenko.house.controllers.outside.class: Jenko\HouseBundle\Controller\OutsideController
    jenko.house.controllers.enter_room.class: Jenko\HouseBundle\Controller\EnterRoomController

services:
    jenko.house.controllers.outside:
        class: %jenko.house.controllers.outside.class%
        arguments:
            - @templating

    jenko.house.controllers.enter_room:
        class: %jenko.house.controllers.enter_room.class%
        arguments:
            - @templating
            - @tabbi89_commander.command.default_command_bus

    jenko.house.handlers.enter_room_handler:
        class: Jenko\House\Handler\EnterRoomHandler
        arguments:
            - @jenko.house.adapters.commander_event_dispatcher

    jenko.house.adapters.commander_enter_room_handler:
        class: Jenko\House\Adapter\CommanderEnterRoomHandlerAdapter
        arguments:
            - @jenko.house.handlers.enter_room_handler
        tags:
            -  { name: tabbi89_command_handler, alias: EnterRoomHandler }

    jenko.house.adapters.commander_event_dispatcher:
        class: Jenko\House\Adapter\CommanderEventDispatcherAdapter
        arguments:
            - @tabbi89_commander.event.event_dispatcher
